apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        args: ["--dbpath", "/data/db"]
        env:
        - name: MONGO_INIT_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INIT_ROOT_PASSWORD
          value: "password"


---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32000
  type: NodePort


