apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # "password" base64 encoded
  mysql-user-password: dGVzdEAxMjM=  # "test@123" base64 encoded
