apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    test: app
spec:
  replicas: 2
  selector:
    matchLabels:
      test: app
  template:
    metadata:
      name: test-deploy
      labels: 
        test: app
    spec:
      containers:
        - name: test-deploy
          image: nginx:1.21.3
          ports:
            - containerPort: 80 
