apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dp
  labels:
    app: test
  annotations:
    kubernetes.io/change-cause: "Updating the Alpine image of the nginx"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: test-dp
      labels:
        app: test
    spec:
      containers:
      - name: test-dp
        image: nginx:alpine
        ports:
        - containerPort: 80 
