apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy-liveness
  labels:
    app: test-liveness
  namespace: test

spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-liveness
  template:
    metadata:
      name: test-deploy-liveness
      labels:
        app: test-liveness
    spec:
      containers:
      - name: test-deploy
        image: nginx:latest
        livenessProbe:
          exec:
            command:
              - curl
              - localhost
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: probe-service-liveness
  namespace: test
spec:
  selector:
    app: test-liveness
  ports:
    - port: 80
      targetPort: 81
  type: ClusterIP

