apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy-readiness
  labels:
    app: test-readiness
  namespace: test

spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-readiness
  template:
    metadata:
      name: test-deploy-readiness
      labels:
        app: test-readiness
    spec:
      containers:
      - name: test-deploy
        image: nginx:latest
        readinessProbe:
          exec:
            command:
              - curl
              - localhost
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: probe-service-readiness
  namespace: test
spec:
  selector:
    app: test-readiness
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

