apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy-startup
  labels:
    app: test-startup
  namespace: test

spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-startup
  template:
    metadata:
      name: test-deploy-startup
      labels:
        app: test-startup
    spec:
      containers:
      - name: test-deploy
        image: nginx:latest
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: probe-service-startup
  namespace: test
spec:
  selector:
    app: test-startup
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

