apiVersion: v1
kind: Pod
metadata:
  name: last-pod-nginx
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "250m"

